apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: public-service
type: Opaque
data:
  HTPASSWD: YWRtaW46JDJ5JDA1JHgwVURRNlNRdVNSODdrLkJZaS9MbS5kbFpaRWx6bEZUVDhRYXdPQjhhQWlXcWtsNEFJUFFtCgo=
