kind: Service
apiVersion: v1
metadata:
  name: k8sregistry-svc
  namespace: public-service
spec:
  selector:
    app: k8sregistry
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30005
    name: registry-http
---
kind: Pod
apiVersion: v1
metadata:
  name: k8sregistry-deploy
  namespace: public-service
  labels:
    app: k8sregistry
spec:
  volumes:
    - name: config
      configMap:
        name: docker-registry
        items:
          - key: registry-config.yml
            path: config.yml
    - name: htpasswd
      secret:
        secretName: docker-registry
        items:
        - key: HTPASSWD
          path: htpasswd
  containers:
    - name: pregistry
      image: registry:2
      ports:
      - containerPort: 5000
      volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
          readOnly: true
        - name: htpasswd
          mountPath: /auth
          readOnly: true
