kind: PersistentVolume
apiVersion: v1
metadata:
  name: ldap-pv
  namespace: public-service
  labels:
    type: local
spec:
  storageClassName: ldapstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ldappath"
