kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-pv
  namespace: public-service
  labels:
    type: local
spec:
  storageClassName: gitlabstorage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/gitlabpath"
