kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-gitlab
  namespace: public-service
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gitlabstorage"
  resources:
    requests:
      storage: 5Gi
