kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  namespace: public-service
  labels:
    type: local
spec:
  storageClassName: redisstorage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redispath"
