kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  namespace: public-service
  labels:
    type: local
spec:
  storageClassName: jenkinsstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkinspath"
